export default [
    {
        prefix: 'background',
        body: 'background: $1;',
        values: ['initial', 'inherit'],
        description: 'CSS background property: `background: ;`',
    },
    {
        prefix: 'background-clip',
        body: 'background-clip: $1;',
        values: ['border-box', 'padding-box', 'content-box', 'initial', 'inherit'],
        description: 'CSS background-clip property: `background-clip: ;`',
    },
    {
        prefix: 'background-color',
        body: 'background-color: $1;',
        values: ['#', '#000000', '#ffffff', 'transparent', 'initial', 'inherit'],
        description: 'CSS background-color property: `background-color: ;`',
    },
    {
        prefix: 'background-image',
        body: 'background-image: $1;',
        values: ['url("$1")', 'none', 'initial', 'inherit'],
        description: 'CSS background-image property: `background-image: ;`',
    },
    {
        prefix: 'background-origin',
        body: 'background-origin: $1;',
        values: ['padding-box', 'border-box', 'content-box', 'initial', 'inherit'],
        description: 'CSS background-origin property: `background-origin: ;`',
    },
    {
        prefix: 'background-position',
        body: 'background-position: $1;',
        values: ['initial', 'inherit'],
        description: 'CSS background-position property: `background-position: ;`',
    },
    {
        prefix: 'background-repeat',
        body: 'background-repeat: $1;',
        values: ['repeat', 'repeat-x', 'repeat-y', 'no-repeat', 'initial', 'inherit'],
        description: 'CSS background-repeat property: `background-repeat: ;`',
    },
    {
        prefix: 'background-size',
        body: 'background-size: $1;',
        values: ['auto', 'cover', 'contain', 'initial', 'inherit'],
        description: 'CSS background-size property: `background-size: ;`',
    },
    {
        prefix: 'border',
        body: 'border: $1;',
        values: ['1px solid #', '1px solid #000000', '1px solid #ffffff', 'initial', 'inherit'],
        description: 'CSS border property: `border: ;`',
    },
    {
        prefix: 'border-bottom',
        body: 'border-bottom: $1;',
        values: ['1px solid #', '1px solid #000000', '1px solid #ffffff', 'initial', 'inherit'],
        description: 'CSS border-bottom property: `border-bottom: ;`',
    },
    {
        prefix: 'border-bottom-color',
        body: 'border-bottom-color: $1;',
        values: ['#', '#000000', '#ffffff', 'transparent', 'initial', 'inherit'],
        description: 'CSS border-bottom-color property: `border-bottom-color: ;`',
    },
    {
        prefix: 'border-bottom-left-radius',
        body: 'border-bottom-left-radius: $1;',
        values: ['$1px', '$1%', 'initial', 'inherit'],
        description: 'CSS border-bottom-left-radius property: `border-bottom-left-radius: ;`',
    },
    {
        prefix: 'border-bottom-right-radius',
        body: 'border-bottom-right-radius: $1;',
        values: ['$1px', '$1%', 'initial', 'inherit'],
        description: 'CSS border-bottom-right-radius property: `border-bottom-right-radius: ;`',
    },
    {
        prefix: 'border-bottom-style',
        body: 'border-bottom-style: $1;',
        values: [
            'none',
            'hidden',
            'dotted',
            'dashed',
            'solid',
            'double',
            'groove',
            'ridge',
            'inset',
            'outset',
            'initial',
            'inherit',
        ],
        description: 'CSS border-bottom-style property: `border-bottom-style: ;`',
    },
    {
        prefix: 'border-bottom-width',
        body: 'border-bottom-width: $1;',
        values: ['$1px', 'medium', 'thin', 'thick', 'initial', 'inherit'],
        description: 'CSS border-bottom-width property: `border-bottom-width: ;`',
    },
    {
        prefix: 'border-collapse',
        body: 'border-collapse: $1;',
        values: ['separate', 'collapse', 'initial', 'inherit'],
        description: 'CSS border-collapse property: `border-collapse: ;`',
    },
    {
        prefix: 'border-color',
        body: 'border-color: $1;',
        values: ['#', '#000000', '#ffffff', 'transparent', 'initial', 'inherit'],
        description: 'CSS border-color property: `border-color: ;`',
    },
    {
        prefix: 'border-left',
        body: 'border-left: $1;',
        values: ['1px solid #', 'initial', 'inherit'],
        description: 'CSS border-left property: `border-left: ;`',
    },
    {
        prefix: 'border-left-color',
        body: 'border-left-color: $1;',
        values: ['#', '#000000', '#ffffff', 'transparent', 'initial', 'inherit'],
        description: 'CSS border-left-color property: `border-left-color: ;`',
    },
    {
        prefix: 'border-left-style',
        body: 'border-left-style: $1;',
        values: [
            'none',
            'hidden',
            'dotted',
            'dashed',
            'solid',
            'double',
            'groove',
            'ridge',
            'inset',
            'outset',
            'initial',
            'inherit',
        ],
        description: 'CSS border-left-style property: `border-left-style: ;`',
    },
    {
        prefix: 'border-left-width',
        body: 'border-left-width: $1;',
        values: ['$1px', 'medium', 'thin', 'thick', 'initial', 'inherit'],
        description: 'CSS border-left-width property: `border-left-width: ;`',
    },
    {
        prefix: 'border-radius',
        body: 'border-radius: $1;',
        values: ['$1px', '$1%', 'initial', 'inherit'],
        description: 'CSS border-radius property: `border-radius: ;`',
    },
    {
        prefix: 'border-right',
        body: 'border-right: $1;',
        values: ['1px solid #', '1px solid #000000', '1px solid #ffffff', 'initial', 'inherit'],
        description: 'CSS border-right property: `border-right: ;`',
    },
    {
        prefix: 'border-right-color',
        body: 'border-right-color: $1;',
        values: ['#', '#000000', '#ffffff', 'transparent', 'initial', 'inherit'],
        description: 'CSS border-right-color property: `border-right-color: ;`',
    },
    {
        prefix: 'border-right-style',
        body: 'border-right-style: $1;',
        values: [
            'none',
            'hidden',
            'dotted',
            'dashed',
            'solid',
            'double',
            'groove',
            'ridge',
            'inset',
            'outset',
            'initial',
            'inherit',
        ],
        description: 'CSS border-right-style property: `border-right-style: ;`',
    },
    {
        prefix: 'border-right-width',
        body: 'border-right-width: $1;',
        values: ['$1px', 'medium', 'thin', 'thick', 'initial', 'inherit'],
        description: 'CSS border-right-width property: `border-right-width: ;`',
    },
    {
        prefix: 'border-style',
        body: 'border-style: $1;',
        values: [
            'none',
            'hidden',
            'dotted',
            'dashed',
            'solid',
            'double',
            'groove',
            'ridge',
            'inset',
            'outset',
            'initial',
            'inherit',
        ],
        description: 'CSS border-style property: `border-style: ;`',
    },
    {
        prefix: 'border-top',
        body: 'border-top: $1;',
        values: ['1px solid #', 'initial', 'inherit'],
        description: 'CSS border-top property: `border-top: ;`',
    },
    {
        prefix: 'border-top-color',
        body: 'border-top-color: $1;',
        values: ['#', '#000000', '#ffffff', 'transparent', 'initial', 'inherit'],
        description: 'CSS border-top-color property: `border-top-color: ;`',
    },
    {
        prefix: 'border-top-left-radius',
        body: 'border-top-left-radius: $1;',
        values: ['$1px', '$1%', 'initial', 'inherit'],
        description: 'CSS border-top-left-radius property: `border-top-left-radius: ;`',
    },
    {
        prefix: 'border-top-right-radius',
        body: 'border-top-right-radius: $1;',
        values: ['$1px', '$1%', 'initial', 'inherit'],
        description: 'CSS border-top-right-radius property: `border-top-right-radius: ;`',
    },
    {
        prefix: 'border-top-style',
        body: 'border-top-style: $1;',
        values: [
            'none',
            'hidden',
            'dotted',
            'dashed',
            'solid',
            'double',
            'groove',
            'ridge',
            'inset',
            'outset',
            'initial',
            'inherit',
        ],
        description: 'CSS border-top-style property: `border-top-style: ;`',
    },
    {
        prefix: 'border-top-width',
        body: 'border-top-width: $1;',
        values: ['$1px', 'medium', 'thin', 'thick', 'initial', 'inherit'],
        description: 'CSS border-top-width property: `border-top-width: ;`',
    },
    {
        prefix: 'border-width',
        body: 'border-width: $1;',
        values: ['$1px', 'medium', 'thin', 'thick', 'initial', 'inherit'],
        description: 'CSS border-width property: `border-width: ;`',
    },
    {
        prefix: 'color',
        body: 'color: $1;',
        values: ['#', '#000000', '#ffffff', 'initial', 'inherit'],
        description: 'CSS color property: `color: ;`',
    },
    {
        prefix: 'display',
        body: 'display: $1;',
        values: [
            'inline',
            'block',
            'inline-block',
            'inline-table',
            'list-item',
            'table',
            'table-caption',
            'table-column-group',
            'table-header-group',
            'table-footer-group',
            'table-row-group',
            'table-cell',
            'table-column',
            'table-row',
            'none',
            'initial',
            'inherit',
        ],
        description: 'CSS display property: `display: ;`',
    },
    {
        prefix: 'font',
        body: 'font: $1;',
        values: [
            '400 16px Arial, sans-serif',
            'caption',
            'icon',
            'menu',
            'message-box',
            'small-caption',
            'status-bar',
            'initial',
            'inherit',
        ],
        description: 'CSS font property: `font: ;`',
    },
    {
        prefix: 'font-family',
        body: 'font-family: $1;',
        values: ['Arial, sans-serif', 'initial', 'inherit'],
        description: 'CSS font-family property: `font-family: ;`',
    },
    {
        prefix: 'font-size',
        body: 'font-size: $1;',
        values: [
            '$1px',
            '$1%',
            'medium',
            'xx-small',
            'x-small',
            'small',
            'large',
            'x-large',
            'xx-large',
            'smaller',
            'larger',
            'length',
            'initial',
            'inherit',
        ],
        description: 'CSS font-size property: `font-size: ;`',
    },
    {
        prefix: 'font-style',
        body: 'font-style: $1;',
        values: ['normal', 'italic', 'oblique', 'initial', 'inherit'],
        description: 'CSS font-style property: `font-style: ;`',
    },
    {
        prefix: 'font-variant',
        body: 'font-variant: $1;',
        values: ['normal', 'small-caps', 'initial', 'inherit'],
        description: 'CSS font-variant property: `font-variant: ;`',
    },
    {
        prefix: 'font-weight',
        body: 'font-weight: $1;',
        values: [
            '100',
            '200',
            '300',
            '400',
            '500',
            '600',
            '700',
            '800',
            '900',
            'normal',
            'bold',
            'bolder',
            'lighter',
            'initial',
            'inherit',
        ],
        description: 'CSS font-weight property: `font-weight: ;`',
    },
    {
        prefix: 'height',
        body: 'height: $1;',
        values: ['$1px', 'auto', 'initial', 'inherit'],
        description: 'CSS height property: `height: ;`',
    },
    {
        prefix: 'letter-spacing',
        body: 'letter-spacing: $1;',
        values: ['$1px', 'normal', 'initial', 'inherit'],
        description: 'CSS letter-spacing property: `letter-spacing: ;`',
    },
    {
        prefix: 'line-height',
        body: 'line-height: $1;',
        values: ['$1px', 'normal', 'initial', 'inherit'],
        description: 'CSS line-height property: `line-height: ;`',
    },
    {
        prefix: 'list-style',
        body: 'list-style: $1;',
        values: ['initial', 'inherit'],
        description: 'CSS list-style property: `list-style: ;`',
    },
    {
        prefix: 'list-style-position',
        body: 'list-style-position: $1;',
        values: ['inside', 'outside', 'initial', 'inherit'],
        description: 'CSS list-style-position property: `list-style-position: ;`',
    },
    {
        prefix: 'list-style-type',
        body: 'list-style-type: $1;',
        values: [
            'disc',
            'circle',
            'decimal',
            'decimal-leading-zero',
            'lower-alpha',
            'lower-latin',
            'lower-roman',
            'none',
            'square',
            'upper-alpha',
            'upper-latin',
            'upper-roman',
            'initial',
            'inherit',
        ],
        description: 'CSS list-style-type property: `list-style-type: ;`',
    },
    {
        prefix: 'opacity',
        body: 'opacity: $1;',
        values: ['initial', 'inherit'],
        description: 'CSS opacity property: `opacity: ;`',
    },
    {
        prefix: 'padding-bottom',
        body: 'padding-bottom: $1;',
        values: ['$1px', 'initial', 'inherit'],
        description: 'CSS padding-bottom property: `padding-bottom: ;`',
    },
    {
        prefix: 'padding-left',
        body: 'padding-left: $1;',
        values: ['$1px', 'initial', 'inherit'],
        description: 'CSS padding-left property: `padding-left: ;`',
    },
    {
        prefix: 'padding-right',
        body: 'padding-right: $1;',
        values: ['$1px', 'initial', 'inherit'],
        description: 'CSS padding-right property: `padding-right: ;`',
    },
    {
        prefix: 'padding-top',
        body: 'padding-top: $1;',
        values: ['$1px', 'initial', 'inherit'],
        description: 'CSS padding-top property: `padding-top: ;`',
    },
    {
        prefix: 'table-layout',
        body: 'table-layout: $1;',
        values: ['auto', 'fixed', 'initial', 'inherit'],
        description: 'CSS table-layout property: `table-layout: ;`',
    },
    {
        prefix: 'text-align',
        body: 'text-align: $1;',
        values: ['left', 'right', 'center', 'justify', 'initial', 'inherit'],
        description: 'CSS text-align property: `text-align: ;`',
    },
    {
        prefix: 'text-align-last',
        body: 'text-align-last: $1;',
        values: [
            'auto',
            'left',
            'right',
            'center',
            'justify',
            'start',
            'end',
            'initial',
            'inherit',
        ],
        description: 'CSS text-align-last property: `text-align-last: ;`',
    },
    {
        prefix: 'text-decoration',
        body: 'text-decoration: $1;',
        values: ['none', 'underline', 'overline', 'line-through', 'initial', 'inherit'],
        description: 'CSS text-decoration property: `text-decoration: ;`',
    },
    {
        prefix: 'text-decoration-color',
        body: 'text-decoration-color: $1;',
        values: ['#', '#000000', '#ffffff', 'initial', 'inherit'],
        description: 'CSS text-decoration-color property: `text-decoration-color: ;`',
    },
    {
        prefix: 'text-decoration-line',
        body: 'text-decoration-line: $1;',
        values: ['none', 'underline', 'overline', 'line-through', 'initial', 'inherit'],
        description: 'CSS text-decoration-line property: `text-decoration-line: ;`',
    },
    {
        prefix: 'text-decoration-style',
        body: 'text-decoration-style: $1;',
        values: ['solid', 'double', 'dotted', 'dashed', 'wavy', 'initial', 'inherit'],
        description: 'CSS text-decoration-style property: `text-decoration-style: ;`',
    },
    {
        prefix: 'vertical-align',
        body: 'vertical-align: $1;',
        values: [
            'baseline',
            'sub',
            'super',
            'top',
            'text-top',
            'middle',
            'bottom',
            'text-bottom',
            'initial',
            'inherit',
        ],
        description: 'CSS vertical-align property: `vertical-align: ;`',
    },
    {
        prefix: 'white-space',
        body: 'white-space: $1;',
        values: ['normal', 'nowrap', 'pre', 'pre-line', 'pre-wrap', 'initial', 'inherit'],
        description: 'CSS white-space property: `white-space: ;`',
    },
    {
        prefix: 'width',
        body: 'width: $1;',
        values: ['$1px', '$1%', 'auto', 'initial', 'inherit'],
        description: 'CSS width property: `width: ;`',
    },
    {
        prefix: 'word-break',
        body: 'word-break: $1;',
        values: ['normal', 'break-all', 'keep-all', 'initial', 'inherit'],
        description: 'CSS word-break property: `word-break: ;`',
    },
    {
        prefix: 'word-spacing',
        body: 'word-spacing: $1;',
        values: ['$1px', 'normal', 'initial', 'inherit'],
        description: 'CSS word-spacing property: `word-spacing: ;`',
    },
    {
        prefix: 'word-wrap',
        body: 'word-wrap: $1;',
        values: ['normal', 'break-word', 'initial', 'inherit'],
        description: 'CSS word-wrap property: `word-wrap: ;`',
    },
    {
        prefix: 'z-index',
        body: 'z-index: $1;',
        values: ['auto', 'initial', 'inherit'],
        description: 'CSS z-index property: `z-index: ;`',
    },
]
